/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import model.Employee;
import service.DepartmentService;
import service.EmployeeService;
import service.PostionService;
import view.CRUD_View.Employee_Add;
import view.CRUD_View.Employee_Edit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jonny Dam
 */
public class EmployeeJPanel extends javax.swing.JPanel {

    private EmployeeService employeeService;
       private DepartmentService departmentService;
    private PostionService postionService;
    public DefaultTableModel getModelTable() {
        DefaultTableModel model = (DefaultTableModel) jTable_16.getModel();
        return model;
    }

    public void searchTable(String value) {
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(getModelTable());
        jTable_16.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(value));
    }

    DefaultTableModel defaultTableModel;

    public EmployeeJPanel() {
         departmentService = new DepartmentService();
        postionService = new PostionService();
        initComponents();

        employeeService = new EmployeeService();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable_16.setModel(defaultTableModel);
        defaultTableModel.addColumn("id");
        defaultTableModel.addColumn("name");
        defaultTableModel.addColumn("department");
        defaultTableModel.addColumn("position");
        defaultTableModel.addColumn("sex");
        defaultTableModel.addColumn("birthday");
        defaultTableModel.addColumn("email");
        defaultTableModel.addColumn("tel");
        try {
            setTableData(employeeService.getAllEmployee());
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
              //design table
         jTable_16.setModel(defaultTableModel);
        jTable_16.getTableHeader().setOpaque(false);
        
//        header design
            DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
       headerRenderer.setBackground(new Color(102,102,102));
       headerRenderer.setForeground(Color.white);
       headerRenderer.setFont(new Font("Tohoma", Font.BOLD, 18));
       for (int i = 0; i < jTable_16.getModel().getColumnCount(); i++) {
               jTable_16.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
       }
       //design column 
       jTable_16.setGridColor(new Color (51,51,51));
        jTable_16.getTableHeader().setPreferredSize(new Dimension(100, 50));
        jTable_16.setRowHeight(30);
        jTable_16.validate();
        jTable_16.repaint();
        jTable_16.setOpaque(true);
        jTable_16.setFillsViewportHeight(true);
        jTable_16.setBackground( new Color(255,255,255));
    }

    private void setTableData(List<Employee> Employees) {
        for (Employee Employee : Employees) {
            try {
                defaultTableModel.addRow(new Object[]{Employee.getEmployee_Id(), Employee.getEmployee_Name(),departmentService.getDepartmentById(Employee.getDepartment_Id()).getDepartment_Name(),postionService.getPostionById(Employee.getPosition_Id()).getPostion_Name(),Employee.getSex(),Employee.getBirthday(),Employee.getEmail(),Employee.getTel()});
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void refreshTableData(List<Employee> Employees) {
        defaultTableModel.setRowCount(0);
        
        try {
            setTableData(employeeService.getAllEmployee());
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_search_16 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_16 = new javax.swing.JTable();
        jButton_Refresh_16 = new javax.swing.JButton();
        jButton_Add_16 = new javax.swing.JButton();
        jButton_Edit_16 = new javax.swing.JButton();
        jButton_Del_16 = new javax.swing.JButton();
        jLabel_DpScreen_16 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(899, 598));

        jTextField_search_16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_search_16.setText("Search");
        jTextField_search_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_search_16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_search_16FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_search_16FocusLost(evt);
            }
        });
        jTextField_search_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_search_16ActionPerformed(evt);
            }
        });
        jTextField_search_16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search_16KeyReleased(evt);
            }
        });

        jTable_16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_16.setShowGrid(true);
        jScrollPane1.setViewportView(jTable_16);

        jButton_Refresh_16.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Refresh_16.setText("Refresh");
        jButton_Refresh_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Refresh_16ActionPerformed(evt);
            }
        });

        jButton_Add_16.setBackground(new java.awt.Color(40, 133, 55));
        jButton_Add_16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add_16.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_16.setText("ADD");
        jButton_Add_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_16ActionPerformed(evt);
            }
        });

        jButton_Edit_16.setBackground(new java.awt.Color(25, 114, 219));
        jButton_Edit_16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Edit_16.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_16.setText("EDIT");
        jButton_Edit_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_16ActionPerformed(evt);
            }
        });

        jButton_Del_16.setBackground(new java.awt.Color(237, 74, 74));
        jButton_Del_16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Del_16.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Del_16.setText("DELETE");
        jButton_Del_16.setPreferredSize(new java.awt.Dimension(80, 21));
        jButton_Del_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Del_16ActionPerformed(evt);
            }
        });

        jLabel_DpScreen_16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_DpScreen_16.setForeground(new java.awt.Color(119, 119, 119));
        jLabel_DpScreen_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoir_group.png"))); // NOI18N
        jLabel_DpScreen_16.setText("Employee Screen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_DpScreen_16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Add_16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Edit_16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Del_16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField_search_16, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Refresh_16)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel_DpScreen_16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_search_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Refresh_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Edit_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Del_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_search_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_search_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_search_16ActionPerformed

    private void jTextField_search_16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search_16KeyReleased
        searchTable(jTextField_search_16.getText());
    }//GEN-LAST:event_jTextField_search_16KeyReleased

    private void jButton_Refresh_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Refresh_16ActionPerformed

        try {
            refreshTableData(employeeService.getAllEmployee());
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_Refresh_16ActionPerformed

    private void jButton_Add_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_16ActionPerformed

        new Employee_Add().setVisible(true);
        
    }//GEN-LAST:event_jButton_Add_16ActionPerformed

    private void jButton_Edit_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_16ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) jTable_16.getModel();
        int id = Integer.parseInt(tblModel.getValueAt(jTable_16.getSelectedRow(), 0).toString());
        System.out.println(id);
        new Employee_Edit(id).setVisible(true);
    }//GEN-LAST:event_jButton_Edit_16ActionPerformed

    private void jButton_Del_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Del_16ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) jTable_16.getModel();
        int id = Integer.parseInt(tblModel.getValueAt(jTable_16.getSelectedRow(), 0).toString());

        try {
            employeeService.deleteEmployee(id);
            refreshTableData(employeeService.getAllEmployee());
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_Del_16ActionPerformed

    private void jTextField_search_16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_search_16FocusGained
               if(jTextField_search_16.getText().equals("Search"))
            jTextField_search_16.setText("");
    }//GEN-LAST:event_jTextField_search_16FocusGained

    private void jTextField_search_16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_search_16FocusLost
                if(jTextField_search_16.getText().equals(""))
            jTextField_search_16.setText("Search");
    }//GEN-LAST:event_jTextField_search_16FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_16;
    private javax.swing.JButton jButton_Del_16;
    private javax.swing.JButton jButton_Edit_16;
    private javax.swing.JButton jButton_Refresh_16;
    private javax.swing.JLabel jLabel_DpScreen_16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_16;
    private javax.swing.JTextField jTextField_search_16;
    // End of variables declaration//GEN-END:variables
}
